### ISSUE TITLE
How to build and run gradle project documentation

### ISSUE THREAD

**Issue by Shaenfre** [lolo8304/coding-challenge#2]
Hi there
I am also following the coding challenges and wanted to use your solution as a reference to learn java
I am new to java and gradle and am having difficulty in running your projects on my system
Can you please add additional documentation as how to run your projects locally
TIA

**Comment by Shaenfre** [comment]
Specifically I was trying to run the load balancer challenge (no-5) in my machine but when I am running the command `./gradlew build` I am unable to find any folder by this location `./app/build/install/app/bin/app`(there is no `install` folder inside `./app/build` folder in my case) which is required for running [lb.sh](https://github.com/lolo8304/coding-challenge/blob/main/no-5/lb.sh) and [be.sh](https://github.com/lolo8304/coding-challenge/blob/main/no-5/be.sh) scripts file

**Comment by yannick8610** [comment]
Hi @Shaenfre I agree. I will document it

**Comment by lolo8304** [comment]
Open the folder in your IntelliJ or vscode to the folder of the number eg no-3

every subfolder has its own gradle

**Comment by lolo8304** [comment]
And run gradlew installDist

**Comment by lolo8304** [comment]
I figured out some issues with java 20 and my configuration
please do git pull and the following procedure to build and run

```bash
cd no-5
./gradlew installDist
```

checkout that you hava java version 20 in your path

```bash
java -version
openjdk version "20.0.2" 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9-78)
OpenJDK 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)
```

**Comment by lolo8304** [comment]
I have updated the readme - https://github.com/lolo8304/coding-challenge/blob/main/no-5/readme.md

thanks for bringing this topic as a bug

**Comment by lolo8304** [comment]
please test again

**Comment by Shaenfre** [comment]
Thanks for taking the time to update the readme file
I am able to run no-5 in my system now
